call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'lambdalisue/suda.vim'                 " Ask pass when needed

call plug#end()

let mapleader = ','
nmap <C-P> :Files <CR>
nmap <leader>bs :History<cr>                " Search Files History
