call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

call plug#end()

let mapleader = ','
nmap <C-P> :Files <CR>
nmap <leader>bs :History<cr>                " Search Files History
